#!/bin/bash
#
# release.sh — One-shot release script for slim2diretta.
#
# What it does:
#   1. Reads the version from CMakeLists.txt (project(slim2diretta VERSION)).
#   2. Verifies preconditions (on main, clean tree, tag does not yet exist,
#      CHANGELOG.md has a section for that version).
#   3. Shows a recap and asks for confirmation.
#   4. Tags the current HEAD as vX.Y.Z and pushes the tag.
#   5. Generates the *-minimal.tar.gz via scripts/make-minimal-tarball.sh.
#   6. Creates the GitHub Release with notes extracted from CHANGELOG.md
#      and uploads the minimal tarball as an asset. The standard tarball
#      is auto-generated by GitHub from the tag.
#
# Requirements:
#   - `gh` (GitHub CLI) authenticated to push releases on this repo.
#   - Must be run from the repository root, on the `main` branch, with
#     a clean working tree.
#
# Usage:
#   scripts/release.sh [--no-release]
#
#   --no-release   Stop after generating the tarball (no tag push, no
#                  GitHub release creation). Useful for dry-runs.
#

set -euo pipefail

PROJECT="slim2Diretta"
VERSION_FILE="CMakeLists.txt"
NO_RELEASE=0

for arg in "$@"; do
    case "$arg" in
        --no-release) NO_RELEASE=1 ;;
        -h|--help) sed -n '1,/^$/{/^#/p}' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "Unknown argument: $arg" >&2; exit 2 ;;
    esac
done

# --- Preconditions ---------------------------------------------------------

if [ ! -f "$VERSION_FILE" ] || [ ! -f CHANGELOG.md ] \
   || [ ! -f scripts/make-minimal-tarball.sh ]; then
    echo "ERROR: must be run from the repository root." >&2
    exit 1
fi

if [ "$(git branch --show-current)" != "main" ]; then
    echo "ERROR: must be on the 'main' branch (current: $(git branch --show-current))." >&2
    exit 1
fi

if ! git diff-index --quiet HEAD --; then
    echo "ERROR: working tree has uncommitted changes." >&2
    exit 1
fi

# --- Extract version from CMakeLists.txt -----------------------------------
# Pattern: project(slim2diretta VERSION 1.3.2)

VERSION=$(grep -oP 'project\(slim2diretta VERSION \K[0-9]+\.[0-9]+\.[0-9]+' "$VERSION_FILE" || true)
if [ -z "${VERSION:-}" ]; then
    echo "ERROR: could not extract project VERSION from $VERSION_FILE" >&2
    exit 1
fi
TAG="v${VERSION}"

# --- Verify CHANGELOG has a section for this version -----------------------
# slim2diretta uses: ## v1.3.2 (2026-05-05)

if ! grep -qE "^## v${VERSION} \(" CHANGELOG.md; then
    echo "ERROR: CHANGELOG.md has no '## v${VERSION} (YYYY-MM-DD)' section." >&2
    echo "       Date the entry before releasing." >&2
    exit 1
fi

# --- Tag must not already exist --------------------------------------------

if git rev-parse --verify --quiet "$TAG" >/dev/null; then
    echo "ERROR: tag $TAG already exists locally." >&2
    exit 1
fi
if git ls-remote --tags origin "$TAG" 2>/dev/null | grep -q "$TAG"; then
    echo "ERROR: tag $TAG already exists on origin." >&2
    exit 1
fi

# --- Extract release notes from CHANGELOG ----------------------------------

NOTES=$(awk -v ver="$VERSION" '
    $0 ~ "^## v" ver " \\(" { capturing=1; next }
    /^## v/ && capturing { exit }
    capturing { print }
' CHANGELOG.md | sed '/./,$!d' | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}')

if [ -z "$NOTES" ]; then
    echo "ERROR: extracted release notes are empty for version $VERSION" >&2
    exit 1
fi

# --- Confirm ---------------------------------------------------------------

HEAD_SHA=$(git rev-parse --short HEAD)

echo "═══════════════════════════════════════════════════════════════"
echo "  Release plan for ${PROJECT}"
echo "═══════════════════════════════════════════════════════════════"
echo "  Version       : ${VERSION}"
echo "  Tag           : ${TAG}"
echo "  Commit (HEAD) : ${HEAD_SHA}"
echo "  Branch        : main"
if [ "$NO_RELEASE" = "1" ]; then
    echo "  Mode          : --no-release (tarball only, no tag push, no GitHub release)"
else
    echo "  Mode          : full release (tag, push, tarball, GitHub release)"
fi
echo
echo "  Release notes (extracted from CHANGELOG.md):"
echo "  ─────────────────────────────────────────────────────────────"
echo "$NOTES" | sed 's/^/    /'
echo "  ─────────────────────────────────────────────────────────────"
echo

read -p "Continue? [y/N] " confirm
case "$confirm" in
    y|Y|yes) ;;
    *) echo "Aborted."; exit 0 ;;
esac

# --- Generate minimal tarball ----------------------------------------------

echo
echo "→ Generating minimal tarball..."
TARBALL="${PROJECT}-${TAG}-minimal.tar.gz"
./scripts/make-minimal-tarball.sh "$TAG"

if [ ! -f "$TARBALL" ]; then
    echo "ERROR: tarball $TARBALL was not produced" >&2
    exit 1
fi
echo "  Created: $TARBALL ($(du -h "$TARBALL" | cut -f1))"

if [ "$NO_RELEASE" = "1" ]; then
    echo
    echo "→ --no-release was passed: stopping here."
    echo "  Tag NOT pushed. GitHub release NOT created."
    echo "  You can still inspect $TARBALL and run release.sh again later."
    exit 0
fi

# --- Tag and push ----------------------------------------------------------

echo
echo "→ Tagging ${TAG}..."
git tag "$TAG"
git push origin "$TAG"

# --- Create GitHub release -------------------------------------------------

echo
echo "→ Creating GitHub release..."
if ! command -v gh >/dev/null 2>&1; then
    echo "WARNING: gh CLI not installed — release was tagged + pushed but not published on GitHub." >&2
    echo "         Create the release manually on https://github.com/cometdom/${PROJECT}/releases" >&2
    echo "         Upload asset: $TARBALL" >&2
    exit 1
fi

gh release create "$TAG" \
    --title "$TAG" \
    --notes "$NOTES" \
    "$TARBALL"

echo
echo "═══════════════════════════════════════════════════════════════"
echo "  Release ${TAG} published successfully."
echo "═══════════════════════════════════════════════════════════════"
echo "  Standard tarball : auto-generated by GitHub from the tag"
echo "  Minimal tarball  : uploaded as additional asset ($TARBALL)"
echo
echo "  Visit: https://github.com/cometdom/${PROJECT}/releases/tag/${TAG}"
